// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACuwED9cA6JCokPeoIn1qELnYWxi7Em3U',
    appId: '1:758370052462:web:6797eac2c54f382ee3f97f',
    messagingSenderId: '758370052462',
    projectId: 'delivery-app-flutter-a1184',
    authDomain: 'delivery-app-flutter-a1184.firebaseapp.com',
    databaseURL: 'https://delivery-app-flutter-a1184-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-flutter-a1184.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAINaVH1eQeLuFryAdNLk0U99TOEWgJwZY',
    appId: '1:758370052462:android:4d9d1ab01d575a6ae3f97f',
    messagingSenderId: '758370052462',
    projectId: 'delivery-app-flutter-a1184',
    databaseURL: 'https://delivery-app-flutter-a1184-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-flutter-a1184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdy0xw_5EYEKGTOziSc-ey9HghV2FMg44',
    appId: '1:758370052462:ios:b0f06e436c9d8ad1e3f97f',
    messagingSenderId: '758370052462',
    projectId: 'delivery-app-flutter-a1184',
    databaseURL: 'https://delivery-app-flutter-a1184-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-flutter-a1184.firebasestorage.app',
    androidClientId: '758370052462-23e30s1nmqj0845kdpl0get71fgpme40.apps.googleusercontent.com',
    iosClientId: '758370052462-kvebqrqprhjrkbl6q690qp7oa8fcbl20.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdy0xw_5EYEKGTOziSc-ey9HghV2FMg44',
    appId: '1:758370052462:ios:b0f06e436c9d8ad1e3f97f',
    messagingSenderId: '758370052462',
    projectId: 'delivery-app-flutter-a1184',
    databaseURL: 'https://delivery-app-flutter-a1184-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-flutter-a1184.firebasestorage.app',
    androidClientId: '758370052462-23e30s1nmqj0845kdpl0get71fgpme40.apps.googleusercontent.com',
    iosClientId: '758370052462-kvebqrqprhjrkbl6q690qp7oa8fcbl20.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACuwED9cA6JCokPeoIn1qELnYWxi7Em3U',
    appId: '1:758370052462:web:c425dccd46c52c55e3f97f',
    messagingSenderId: '758370052462',
    projectId: 'delivery-app-flutter-a1184',
    authDomain: 'delivery-app-flutter-a1184.firebaseapp.com',
    databaseURL: 'https://delivery-app-flutter-a1184-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-flutter-a1184.firebasestorage.app',
  );
}
